### ISSUE TITLE
Μετάφραση error debugging guides

### ISSUE THREAD

**Issue by bampakoa** [bampakoa/angular-gr#20]
Στα error debugging guides (π.χ. https://angular-gr.web.app/errors/NG0100) να μεταφραστεί η λέξη `@description` και `@debugging`.

**Comment by bampakoa** [comment]
@gkalpak μήπως μπορείς να βοηθήσεις?

**Comment by gkalpak** [comment]
Αυτά τα λεκτικά ορίζονται στο template για τις σελίδες σφαλμάτων: [aio/tools/transforms/templates/error/error.template.html][1]
Οπότε εκεί πρέπει να γίνει η μετάφραση.

To "description" φαντάζομαι θα γίνει "περιγραφή". Το "debugging the error" όμως? "Αποσφαλμάτωση του σφάλματος"? 😛

[1]: https://github.com/angular/angular/blob/76f5a559e8047113985b5bc2741b96264da32eb9/aio/tools/transforms/templates/error/error.template.html#L21-L31

**Comment by bampakoa** [comment]
**Διερεύνηση προβλήματος** πως σου φαίνεται?
